on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: "arduino:avr:uno"
          sketch-paths:
            "- /arduino"
        
